### ISSUE TITLE
请问可以提供一下全图训练对应的全图推理的代码嘛

### ISSUE THREAD

**Issue by upupbo** [huapohen/general_parking_slot_detection#10]
前辈好，我通过全图训练的模型预测公开数据集发现效果很差，是不是因为用的推理代码是左右两部分的图导致的，可以提供一下全图训练对应的推理代码嘛

**Comment by huapohen** [comment]
我忘记了。但是我但是左全图推理的时候，直接也用是的子图的推理代码，是不是改了啥子我记不到了，画图在dataset文件夹下的process文件，具体哪一个process我也忘了。哎呀，记忆太惨了，你得check一下。 另外，avm文件夹下 是子图 推理的pipeline，改一下尺寸，是可以输入视频直接出图的。  抱歉

**Comment by huapohen** [comment]
前辈好，我通过全图训练的模型预测公开数据集发现效果很差，是不是因为用的推理代码是左右两部分的图导致的，
这个要点 去年有人问过： 一是 分辨率的尺寸设计 512x512 下采样 32倍是 16x16，是不是要用8x8，到底出成哪个分辨率尺寸 对全图训练影响很大。另外 数据增强 旋转的角度 是不是要小一点，这个也有影响。和翻转操作 label的翻转也得跟上。
我当时也只是跑通了全图 推理发现还正常  没有进一步推进。你可以先试试参数两稍稍大一点点，训epoch少一点看看效果。应该1两个小时就能看效果图了吧
 太抱歉了，全图我就搞了 一上午。当时我是怎么搞出来的，记不得了

**Comment by huapohen** [comment]
tongji PS2.0 dataset它的分辨率，我换在 seoul的 PIKparking 子图方式处理时，应该是做了放缩。
![image](https://github.com/huapohen/general_parking_slot_detection/assets/75824121/d6d1a6d2-6b22-4e0e-856e-11c76e21eecb)
然后 弄成512是不是又做了 放缩。因为 我是单尺度出图的，没上多尺度，这个影响也有  到底是 哪个尺度的feature map 32x32 16x16 8x8 ?  I forget。

**Comment by huapohen** [comment]
> 前辈好，我通过全图训练的模型预测公开数据集发现效果很差，是不是因为用的推理代码是左右两部分的图导致的，可以提供一下全图训练对应的推理代码嘛

多尝试一下 这些 尺度 和增强 方面的。 因为一个 gt格子的拿来左回归 4x12图中车位的分布 是比较符合的。  图片的比例变了后，feature map 的 尺寸 影响还是有的。
我现在没法再碰这个了。
祝你成功！

**Comment by huapohen** [comment]
还有 要把 推理时 固定的90度 这个给关掉。   
if params.direction_rectangle:  # fixed rectangle slot 
这个是个奇葩的操作。
先训稍大一点的模型，效果好了后 再训小的

**Comment by upupbo** [comment]
前辈好，我训练全图任务，看到效果一直是0，可以加您微信请教一下嘛，vx:ilovehmq_faithfully

**Comment by upupbo** [comment]
前辈好，这是我设置的参数
        exp_id = 1
        args.gpu_used = '0, 1, 2, 3'
        exp_name = 'parking_slot_20231027_test'
        args.model_dir = f'experiments/{exp_name}/exp_{exp_id}'
        args.tb_path = f'experiments/{exp_name}/tf_log/'
        args.tb_path += f'{exp_name}_exp_{exp_id}'
        args.yolo_depth = 1
        args.yolo_width = 1
        # args.yolo_width = 0.5
        args.head_width = args.yolo_width
        args.fix_expand = True
        args.model_type = 'dark'
        args.upsample_type = 'bilinear'
        args.dwconv = False
        args.shift_w_ratio = 0
        args.shift_h_pixel = 1/12*2
        args.new_flip_h_ratio = 0
        args.learning_rate = 0.001
        args.angle_range = 15
        args.squared_distance_thresh = 0.005 # big
        args.occupied_mode = False
        args.train_batch_size = 128
        args.num_workers = 8
        args.eval_freq = 1
        args.train_data_ratio = [["fullimg", 1]]
        args.val_data_ratio = [["fullimg", 1]]
        args.major_metric = 'Recall'
        args.deltanorm_or_direction = 'deltanorm'
        args.data_dir = '/data/public/chenbo/svm_park_slot_detect_new_vision/gpsd_datasets'
        cacl_flop = 1
