### ISSUE TITLE
psv数据集的下载链接可以提供一下嘛

### ISSUE THREAD

**Issue by upupbo** [huapohen/general_parking_slot_detection#11]
PSV　[Resourse - TiEV research](https://link.zhihu.com/?target=http%3A//cs1.tongji.edu.cn/tiev/resourse/)3 PSV
这个链接打不开，能不能提供一下云盘下载链接

**Comment by huapohen** [comment]
在issue 已关闭的问题里 我贴了有，链接我复制如下：https://pan.baidu.com/s/1wJKy1w1W6LLkQcG5fHQLDA?pwd=gpsd 
目录里的tongji.zip

**Comment by huapohen** [comment]
哦  我回答错了，PSV，这个语义分割的 我没有。
