### ISSUE TITLE
继续训练，载入图片报错

### ISSUE THREAD

**Issue by liutangming** [huapohen/general_parking_slot_detection#13]
大佬，请教下，我使用search_hyperparams.py生成的参数json文件，但载入后报错：
File "train.py", line 299, in <module>
    dataloaders = data_loader.fetch_dataloader(params)
  File "/home/lto5sgh/2023-parking-slots/general_parking_slot_detection-master/dataset/data_loader.py", line 525, in fetch_dataloader
    train_ds = AutoParkingData(params, mode="train")
  File "/home/lto5sgh/2023-parking-slots/general_parking_slot_detection-master/dataset/data_loader.py", line 54, in __init__
    percentage = int(len(imgs_file) * data_ratio[1])
ValueError: invalid literal for int() with base 10: 'eee'
我在Train.py中再次添加一遍
args.train_data_ratio = [["seoul", 1]]
args.val_data_ratio = [["seoul", 1]]
即可运行，但我添加的内容和json中是一致的，请问问题点在哪儿？如下是json的配置：
"train_data_ratio": [
        "seoul",
        1
    ],
    "val_data_ratio": [
        "seoul",
        1
    ],

**Comment by liutangming** [comment]
找到问题点了，应该是生成json参数的脚本问题，当只有一个数据集时，生成的json文件，少了个方括号，修改json为如下即可：
"train_data_ratio": [[
        "seoul",
        1
    ]],
    "val_data_ratio": [[
        "seoul",
        1
    ]],

**Comment by huapohen** [comment]
> 找到问题点了，应该是生成json参数的脚本问题，当只有一个数据集时，生成的json文件，少了个方括号，修改json为如下即可： "train_data_ratio": [[ "seoul", 1 ]], "val_data_ratio": [[ "seoul", 1 ]],

You're right !
