### ISSUE TITLE
请问下你说效果不好是目标点预测不好，还是偏移回归不好？

### ISSUE THREAD

**Issue by John-T7** [huapohen/general_parking_slot_detection#14]
看到你的偏移是在归一化中的差值，可能就不是（-1，1）的均匀区间，反而可能是（-0.3，0.3）的区间。
而预测结果是用tanh函数激活的，这是不是结果不好的原因。
如果对偏移的长度单独归一化可以么？
或者说根本不是因为这个问题！而是你的图像缩嘚太小，网络模型结构不够复杂呢？

**Comment by huapohen** [comment]
> 看到你的偏移是在归一化中的差值，可能就不是（-1，1）的均匀区间，反而可能是（-0.3，0.3）的区间。

这个我记不起了

**Comment by huapohen** [comment]
> 而预测结果是用tanh函数激活的，这是不是结果不好的原因。

一开始我想过三角函数可能会导致的问题，后续发现tanh能出效果，就还是采用了。  效果不好会出现在分隔线的角度偏差上

**Comment by huapohen** [comment]
> 如果对偏移的长度单独归一化可以么？

你可以试试，我记不起当时对这个的考虑了

**Comment by huapohen** [comment]
> 或者说根本不是因为这个问题！而是你的图像缩嘚太小，网络模型结构不够复杂呢？

网络参数量和flops太小，角度偏差会很明显，网络大一点偏差就会很小了。  但图片的分辨率和feature map的大小选择 会影响最终效果
