### ISSUE TITLE
关于训练的时候，sepline角度计算的问题

### ISSUE THREAD

**Issue by yongguanjiangshan** [huapohen/general_parking_slot_detection#17]
你好，非常感谢你的分享。想请教你一下，计算loss的时候，当deltanorm_or_direction是direction时，我看sepline的角度是用如下代码
```
x_ratio, y_ratio = 1, H / W
radian = math.atan2(marking_point.lenSepLine_y * y_ratio, marking_point.lenSepLine_x * x_ratio)
```
你能说明一下，为什么需要乘以y_ratio和x_ratio吗？

**Comment by huapohen** [comment]
> 你好，非常感谢你的分享。想请教你一下，计算loss的时候，当deltanorm_or_direction是direction时，我看sepline的角度是用如下代码
> 
> ```
> x_ratio, y_ratio = 1, H / W
> radian = math.atan2(marking_point.lenSepLine_y * y_ratio, marking_point.lenSepLine_x * x_ratio)
> ```
> 
> 你能说明一下，为什么需要乘以y_ratio和x_ratio吗？

因为 384 / 128 = 3，H/W=3，实际上，你看斜率 是不是应该乘以3倍？，因为我是归一化到 1来做的。
