### ISSUE TITLE
请问在哪能看到用的是哪个网络呢

### ISSUE THREAD

**Issue by LUOljw** [huapohen/general_parking_slot_detection#18]

**Comment by huapohen** [comment]
> _No description provided._

        ./train.py里 args.model_type = 'dark'
        ./model/net.py 第10行 elif params.net_type == "yolox_single_scale":
        ./model/yolox_single_scale.py 第62行 if model_type in ['dark', 'default']:

        experiments/params.json 里
              第25/26行 "net_type": "yolox_single_scale",  "model_type": "dark",
