### ISSUE TITLE
车位描述定义

### ISSUE THREAD

**Issue by Heikozhu** [huapohen/general_parking_slot_detection#19]
您好, 想请教个问题, 如果车位的A点被截断(即位于图片之外), 这样的车位需要标注么? 另外算法里回归的是AB的长度, 所以个人理解, 如果B点位于图片之外, 这种车位也不标注对么?
也就是说, 本算法所要求的标注, 只有当A, B两点(无论是否遮挡)都位于图片内时才标注该车位, 对吗？

**Comment by huapohen** [comment]
> 您好, 想请教个问题, 如果车位的A点被截断(即位于图片之外), 这样的车位需要标注么? 另外算法里回归的是AB的长度, 所以个人理解, 如果B点位于图片之外, 这种车位也不标注对么? 也就是说, 本算法所要求的标注, 只有当A, B两点(无论是否遮挡)都位于图片内时才标注该车位, 对吗？

AB都在图片内才标注，是的
