### ISSUE TITLE
转换脚本

### ISSUE THREAD

**Issue by zhanghongsir** [huapohen/general_parking_slot_detection#3]
请问可以重新提供转换脚本吗
https://github.com/dohoseok/context-based-parking-slot-detect/
项目里没有转换脚本

**Comment by huapohen** [comment]
没有转换脚本，PS2.0_convert 用PIL-park（seoul）数据集论文就行了。它相当于重新制作了下。而我在后续自己造数据集的时候，打标可以按 GPSD的打标法打，把分割线（指方向那根线）直接顶到图像边缘打，用的时候，可用方向，也可用（delta）
