### ISSUE TITLE
子图训练，斜方向车位分割线sin cos角度预测的不好

### ISSUE THREAD

**Issue by zhanghongsir** [huapohen/general_parking_slot_detection#5]
子图训练，斜方向车位分割线sin cos角度预测的不好,斜方向的车位类型预测出来基本都是与车位入口线垂直，但是ap精度确依然很高，ps2.0达到了99.54。
请问是训练集缺少这种图片的原因吗?

**Comment by huapohen** [comment]
1. 推理要关掉 固定画矩形车位
2. flops 在极低（几十MFlops）的时候，会出现一些这种现象，flops控制得不要太低
3. 在DMPR-PS的基础上，它的方向训练得非常准，我加了delta，而且在loss权重里把delta损失的权重赋予得更大，方向更小。
4. PIL_park（seoul）训练集有太多这种图片，而PS2.0却没得。

https://github.com/huapohen/general_parking_slot_detection/blob/6923356f13eea2eb7cd20b10095a3545f7e04f44/loss/losses.py#L179 
entry = (pd[:, 5:7] - gt[:, 5:7])**2 * 10
others = (pd[:, 1:5] - gt[:, 1:5])**2

**Comment by huapohen** [comment]
在DMPR-PS的基础上，它的方向训练得非常准，我加了delta，而且在loss权重里把delta损失的权重赋予得更大。
PIL_park（seoul）训练集有太多这种图片，而PS2.0却没得。

**Comment by zhanghongsir** [comment]
感谢答复，训练和推理和推理的时候，direction_rectangle已经设为false，并且用的模型比较大,  flops为6117M。这个时候进行训练和推理，我发现deltanorm_or_direction设置为direction会出现上述情况，设置为deltanorm可以进行准确预测。

**Comment by huapohen** [comment]
6G太大了，没必要，几百M就相当好了。至于为什么会出现这种情况，我当初是怎么处理的，忘了。。。哈哈，你可以用 deltanorm吧 转一下就好。  这个项目  我不敢放出来，知乎放了一下马上又关了。因为有公众号联系我，放出来会被转，被一些人看见了就不好了。

**Comment by huapohen** [comment]
讲道理，”方向“ 结果应该大于等于 DMPR-PS的准度，可以尝试把权重大头赋给它

**Comment by huapohen** [comment]
我在实际应用中，要求只搞了大多数的矩形，项目要我把方向关了，所以我后来没去解方向有时失偏的问题，但是我认为 可以解的（DMPR-PS只搞方向不就是这样来的吗，，可以做几个实验）
entry = (pd[:, 5:7] - gt[:, 5:7])**2
others = (pd[:, 1:5] - gt[:, 1:5])**2 * 10
试试吧 loss多了，或许这样解效果不定达期望。
我一年没碰这个项目了。

**Comment by zhanghongsir** [comment]
好的好的，十分感谢您的回答，我会尝试一下。
