### ISSUE TITLE
权重文件大小问题

### ISSUE THREAD

**Issue by xingxinghaq** [huapohen/general_parking_slot_detection#7]
您好，我想请教一下，为什么我用train.py进行训练，用的yolox_single_scale网络模型，保存下来的权重文件有180多MB呀，我看您这边提供的权重文件有的只有9MB大小，想知道您是怎么做到的

**Comment by huapohen** [comment]
args.yolo_depth = 1/3
args.yolo_width = 0.25
args.head_width = args.yolo_width
args.model_type = 'dark'
这4个参数，怎么调的，我记不清了，你参考下“实验记录”，在那个链接云文档里

**Comment by huapohen** [comment]
> 

链接 https://www.kdocs.cn/l/cnqdZU59SRuX

**Comment by huapohen** [comment]
> 您好，我想请教一下，为什么我用train.py进行训练，用的yolox_single_scale网络模型，保存下来的权重文件有180多MB呀，我看您这边提供的权重文件有的只有9MB大小，想知道您是怎么做到的

args.yolo_depth = 1/3
args.yolo_width = 0.25
args.head_width = args.yolo_width
args.model_type = 'dark'
这4个参数，怎么调的，你参考下“实验记录”，在那个链接云文档里 "200 exps": https://www.kdocs.cn/l/cnqdZU59SRuX

**Comment by xingxinghaq** [comment]
感谢感谢🌹🌈，重新排查了一下代码，确实是这几个参数我这边设置的太大了ヾ(＠⌒ー⌒＠)ノ
