### ISSUE TITLE
全图预测结果不理想

### ISSUE THREAD

**Issue by Heikozhu** [huapohen/general_parking_slot_detection#8]
您好，我直接使用了您提供的fullimg权重预测ps2.0数据集（全图），预测结果不理想，重新训练了一组权重（在ps2.0上ap达到92%）预测的结果也没有改善，请问预测的时候有什么要调整的地方吗

**Comment by huapohen** [comment]
全图我花的精力比较少，当初只是做了个验证用，可以提供给您建议如下：1. 模型参数稍微设大点试试；2. 旋转角度改小点，比如15°内;  3. 你可以尝试调下loss公式，哪个部分预测效果差就权重加大哪里；4. AP的计算公式，设严格点，重新训搜参提稿网络准确度；**5.** ps2.0这个数据集太简单了！一张图就一两个车位，又大，场合又单一，又是很基本的车位类型，当然泛化性不好！ 建议自己造数据集来训，这个 ps2.0  真不能用！ 
我去年5月后就没碰这个项目了，没进行进一步探索。
额外补充：交流过这个模型可直接接到语义分割和实例分割、目标检测上，作为多任务预测，多出几个头而已，有人验证过可行。

**Comment by huapohen** [comment]
https://github.com/huapohen/NNAVM/blob/dev/dataset/datamaker/bev_from_multi_fev.py#L1690
这里有个 简单的 鱼眼fev 到 鸟瞰bev的python代码（非torch矩阵乘版本），不过可以用来造AVM数据集，你看那个同济ps2.0 拼得不好是吧，光影也没处理，自己用鱼眼的数据造一波需要的场景。参考参考网上的AVM流程，用自己数据训。

**Comment by Heikozhu** [comment]
非常感谢您详细的回答！后续我根据您的建议继续实验。
