### ISSUE TITLE
diy数据集百度网盘链接失效

### ISSUE THREAD

**Issue by upupbo** [huapohen/general_parking_slot_detection#9]
敬爱的前辈好，diy数据集的链接失效了，帮忙重新发一个链接哈

**Comment by huapohen** [comment]
![image](https://github.com/huapohen/general_parking_slot_detection/assets/75824121/0920c29e-2567-492b-b6c8-490ca570b3ea)
【超级会员V6】通过百度网盘分享的文件：gpsd_dat...
链接：https://pan.baidu.com/s/1VdHaSPNH8zM6t3otFvM95g 
提取码：gpsd 
复制这段内容打开「百度网盘APP 即可获取」
你看看，不应该啊，我这边还能点进🤣

**Comment by huapohen** [comment]
哦，我想起来了，就这个我刚贴的链接，也是diy数据集链接下面那个 All in here链接。 是包含所有的数据集。    因为原来的链接，名字命名不能含有benchmark，要被网盘封。在我给的链接里叫做in99
